language: cpp
sudo: false
compiler: clang

matrix:
    include:
        - os: linux
          dist: focal
          compiler: gcc
          env:
              - CONF=debug
              - COMPILER=gcc
        - os: linux
          dist: focal
          compiler: gcc
          env:
              - CONF=release
              - COMPILER=gcc
        - os: linux
          dist: focal
          compiler: clang
          env:
              - CONF=debug
              - COMPILER=clang
        - os: linux
          dist: focal
          compiler: clang
          env:
              - CONF=release
              - COMPILER=clang
        - os: osx
          osx_image: xcode12
          compiler: clang
          env:
              - CONF=debug
              - COMPILER=apple-clang
        - os: osx
          osx_image: xcode12
          compiler: clang
          env:
              - CONF=release
              - COMPILER=apple-clang


addons:
  apt:
    update: true
    packages:
      - libsdl2-dev
      - libgtk2.0-dev


# gcc update grabbed from https://github.com/ldc-developers/ldc/blob/master/.travis.yml
install:
  - ./scripts/travis-dependencies.sh
before_script: ./scripts/travis-cmake.sh
script:
  - make
  - make package

cache:
  directories:
  - $TRAVIS_BUILD_DIR/deps/

deploy:
  provider: bintray
  file: scripts/bintray-${TRAVIS_OS_NAME}-${COMPILER}.json
  user: "madeso"
  key: ${TRAVIS_BINTRAY_SECRET}
  dry-run: false

